<h2>Sign Up </h2>
<div class="alert alert-<?php echo $success === true ? 'success' : 'danger'; ?>">
    <?php echo isset($message)?$message:''; ?>
</div>

<?php echo $this->tag->form("user/signup"); ?>
<p>
    <label for="name">Name</label>
    <?php echo $this->tag->textField("name"); ?>
</p>
<p>
    <label for="email">email</label>
    <?php echo $this->tag->textField("email"); ?>
</p>
<p>
    <label for="password">password</label>
    <?php echo $this->tag->textField("password"); ?>
</p>
<?php echo $this->tag->submitButton("Submit"); ?>
</form>